import os
from dotenv import load_dotenv

load_dotenv()

PPROCEDURE_DB_HOST = os.getenv("PPROCEDURE_DB_HOST")
PPROCEDURE_DB_PORT = int(os.getenv("PPROCEDURE_DB_PORT"))
PPROCEDURE_DB_USERNAME = os.getenv("PPROCEDURE_DB_USERNAME")
PPROCEDURE_DB_PASSWORD = os.getenv("PPROCEDURE_DB_PASSWORD")
PPROCEDURE_DB_DATABASE = os.getenv("PPROCEDURE_DB_DATABASE")
